### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by ken016** [codmpm/esp-sdm-mqtt#2]
Hello, i try this nice Project but..

Arduino IDE say this..

SDM<baud, rxPin, txPin, derePin> sdm;
...
In file included from E:\Projekte\esp-sdm-mqtt-master\esp-sdm-mqtt\esp-sdm-mqtt.ino:18:0:

Tasker.h:92:6: error: initializing argument 1 of 'bool Tasker::setInterval(TaskCallback0, long unsigned int, byte)' [-fpermissive]

 bool Tasker::setInterval(TaskCallback0 func, unsigned long interval, byte prio)

      ^

E:\Projekte\esp-sdm-mqtt-master\esp-sdm-mqtt\esp-sdm-mqtt.ino: In lambda function:

esp-sdm-mqtt:86:20: error: 'class ArduinoOTAClass' has no member named 'getCommand'

     if (ArduinoOTA.getCommand() == U_FLASH) {

                    ^

exit status 1
'SDM' is not a template

Any idea?

Thanks ...

**Comment by codmpm** [comment]
Hey,

check #1 for the correct Tasker library. Obviously they've changed something since I've last visited this project.
For the `ArduinoOTA` stuff, just comment it out. 

As soon as my time allows it, I will fix this project to work on the current Arduino IDE and with the current Tasker library.

Cheers,
Patrik

**Comment by ken016** [comment]
Hello, ok.. so it works..
because, a new SDM Version is online, so i went to the old version.
The correkt Softwareserial and tasker.
And it works..thanks

A nice project.

**Comment by codmpm** [comment]
You're welcome.

Do you mean there is a new SDM-library? Could you provide a link?

Cheers.

**Comment by ken016** [comment]
hey..

this is the new..
https://github.com/reaper7/SDM_Energy_Meter

here this what work with your code..

https://github.com/reaper7/SDM_Energy_Meter/tree/old_template

But i find in espeasy in the development Firmware version, EASTRON SDM  too.
It works out of the Box.
https://github.com/letscontrolit/ESPEasy/releases
Release mega-20190315

just for info.. 
many thanks for help and this fine project :-)

**Comment by codmpm** [comment]
Thank you. Good news!
